name: ci

#on: workflow_dispatch
on:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: 'false'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Create env file'
        run: |
          touch .env
          echo {{ secrets.APP_ENV }} >> .env
          cat .env
          readlink -f .env
          readlink -f package.json

      - name: 'Create .npmrc file'
        run: |
          touch .npmrc
          echo {{ secrets.NPMRC }} >> .npmrc
          cat .npmrc
          readlink -f .npmrc

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: wildegor/nestjs-microservice-boilerplate
