name: ci

on: workflow_dispatch
#on:
#  push:
#    branches:
#      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      issues: read
    steps:
      - uses: actions/checkout@v3
        with:
          clean: 'false'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Create .env file'
        run: |
          echo {{ secrets.APP_ENV }} >> .env

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 'Create .npmrc'
        run: |
          yarn ci:token
        env:
          NODE_ENV_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
          file: ./Dockerfile
